sudo: required
services:
  - docker


before_install:
  - docker build -t saurabhdudeja82/docker-react -f Dockerfile.dev .


script:
  - docker run saurabhdudeja82/docker-react npm run test -- --coverage
