version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        stdin_open: true
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - C:\Users\Dakchi\projects\frontend:/app

        